#!/usr/bin/python3
from Nim import Nim
from NimBase import PlayCondition

if __name__=='__main__':
    s = input("Do you wish to run this program interactively (y = yes) ")
    if s=='y':
        dim = input("Number of Dimensions: ")
        code = input("Quartenary Move Code (or just push enter for regular (1/3) Nim) ")
        play = str()
        while not (play == 'M' or play == 'N'):
            play = input("(M)isere of (N)ormal Play ")

        if play == 'M':
            play = PlayCondition.Misere
        else:
            play = PlayCondition.Normal

        if code == '':
            code = None

        nim = Nim(int(dim), code, play) 
        nim.run()
        print(nim)






